"""SQPulse: A modern framework for quantum pulse engineering,
Transmon dynamics simulation, and experimental calibration.
"""

__version__ = "0.1.0"

from .pulses import (
    Pulse,
    GaussianPulse,
    CosinePulse,
    LorentzianPulse,
    SquarePulse,
    FlatTopPulse,
    SechPulse,
    DRAGPulse,
    CustomPulse,
    ScaledPulse,
    gaussian_pulse,
    cosine_pulse,
    lorentzian_pulse,
    square_pulse,
    flattop_pulse,
    sech_pulse,
    drag_pulse,
    custom_pulse,
    spectral_leakage,
    compare_pulses,
)
from .models import Transmon
from .sequence import PulseSequence, Channel
from .simulation import Simulator, SimulationResult
from .experiments import (
    RabiExperiment,
    RabiResult,
    T1Experiment,
    T1Result,
    RamseyExperiment,
    RamseyResult,
)
from .units import (
    s,
    sec,
    second,
    seconds,
    ms,
    millisecond,
    milliseconds,
    us,
    microsecond,
    microseconds,
    ns,
    nanosecond,
    nanoseconds,
    ps,
    picosecond,
    picoseconds,
    Hz,
    hertz,
    kHz,
    kilohertz,
    MHz,
    megahertz,
    GHz,
    gigahertz,
    rad_s,
    krad_s,
    Mrad_s,
    Grad_s,
)

__all__ = [
    "Pulse",
    "GaussianPulse",
    "CosinePulse",
    "LorentzianPulse",
    "SquarePulse",
    "FlatTopPulse",
    "SechPulse",
    "DRAGPulse",
    "CustomPulse",
    "ScaledPulse",
    "gaussian_pulse",
    "cosine_pulse",
    "lorentzian_pulse",
    "square_pulse",
    "flattop_pulse",
    "sech_pulse",
    "drag_pulse",
    "custom_pulse",
    "spectral_leakage",
    "compare_pulses",
    "Transmon",
    "PulseSequence",
    "Channel",
    "Simulator",
    "SimulationResult",
    "RabiExperiment",
    "RabiResult",
    "T1Experiment",
    "T1Result",
    "RamseyExperiment",
    "RamseyResult",
    "s",
    "sec",
    "second",
    "seconds",
    "ms",
    "millisecond",
    "milliseconds",
    "us",
    "microsecond",
    "microseconds",
    "ns",
    "nanosecond",
    "nanoseconds",
    "ps",
    "picosecond",
    "picoseconds",
    "Hz",
    "hertz",
    "kHz",
    "kilohertz",
    "MHz",
    "megahertz",
    "GHz",
    "gigahertz",
    "rad_s",
    "krad_s",
    "Mrad_s",
    "Grad_s",
]
